name: Project Based Labels

on:
  issues:
    types: [opened, edited]

jobs:
  project-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Project Labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            
            // Verifica se a issue está em um projeto
            const projects = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            for (const project of projects.data) {
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              for (const column of columns.data) {
                if (column.name.toLowerCase().includes('backlog')) {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ['backlog']
                  });
                }
                
                if (column.name.toLowerCase().includes('in progress')) {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ['in-progress']
                  });
                }
              }
            }